from synqtab.evaluators.Evaluator import Evaluator


class DCREvaluator(Evaluator):
    """ Distance from Closest Record Evaluator (Baseline). Leverages
    https://docs.sdv.dev/sdmetrics/data-metrics/privacy/dcrbaselineprotection. Parameters:
        - [*required*] `'real_training_data'`: the real data used to train the generator
        - [*required*] `'synthetic_data'`: the synthetic data generated by the generator
        - [*required*] `'metadata'`: sdmetrics metadata; See 
        https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata
        - [*optional*] `'notes'`: True/False on whether to include notes in the result or not.
        If absent, defaults to False.
    """
    def compute_result(self):
        from sdmetrics.single_table import DCRBaselineProtection
        
        score = DCRBaselineProtection.compute_breakdown(
            real_training_data=self.params.get('real_training_data'),
            synthetic_data=self.params.get('synthetic_data'),
            metadata=self.params.get('metadata'),
        )
        if self.params.get('notes', False):
            return score.get('score'), score.get('median_DCR_to_real_data')
        return score.get('score')
    
    def short_name(self):
        from synqtab.enums import EvaluationMethod
        return str(EvaluationMethod.DCR)
    
    def full_name(self):
        return "Distance from Closest Record Evaluator"
