from synqtab.evaluators.Evaluator import Evaluator


class LogisticDetector(Evaluator):
    """ Logistic Detection Evaluator that leverages SDMetrics Detection with Logistic Regression
        https://docs.sdv.dev/sdmetrics/data-metrics/metrics-in-beta/detection-single-table. Parameters:
        - [*required*] `'real_training_data'`: the real data used to train the generator
        - [*required*] `'synthetic_data'`: the synthetic data generated by the generator
        - [*required*] `'metadata'`: sdmetrics metadata; See 
        https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata
    """
    
    def short_name(self):
        from synqtab.enums import EvaluationMethod
        return str(EvaluationMethod.LGD)
    
    def full_name(self):
        return "Logistic Detection"
        
    def compute_result(self):
        from sdmetrics.single_table import LogisticDetection
        from synqtab.reproducibility import ReproducibleOperations
        
        # Important, otherwise SDMetric's operation returns different results every time
        ReproducibleOperations.seed_everything()
        
        result = LogisticDetection.compute_breakdown(
            real_data=self.params.get('real_training_data'),
            synthetic_data=self.params.get('synthetic_data'),
            metadata=self.params.get('metadata'),
        )
        # example result: {'score': np.float64(0.17222083333333327)}
        
        score = result.get('score').item() # .item() to convert np.float64 to python native float
        notes = dict() # SDMetrics provides no further information for this computation
        return score, notes
