from synqtab.evaluators.Evaluator import Evaluator


class MLAugmentationRegression(Evaluator):
    """ ML Augmentation Regression R2 Efficacy Evaluator. Custom implementation. Parameters:
        - [*required*] `'real_training_data'`: the real data used to train the generator
        - [*required*] `'synthetic_data'`: the synthetic data generated by the generator
        - [*required*] `'prediction_column_name'`: the name of the target column
        - [*required*] `'real_validation_data'`: the data to use for validation (unseen by the generator)
        - [*optional*] `'notes'`: True/False on whether  to include notes in the result or not.
        If absent, defaults to False.
    """
    
    def short_name(self):
        from synqtab.enums import EvaluationMethod
        return str(EvaluationMethod.AR2)
    
    def full_name(self):
        return "ML Augmentation R2"
    
    def is_compatible_with(self, dataset) -> bool:
        from synqtab.enums import ProblemType
        
        return dataset.problem_type == str(ProblemType.REGRESSION)
        
    def compute_result(self):
        import pandas as pd
        from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
        from synqtab.reproducibility import ReproducibleOperations
        
        real_training_data = self.params.get('real_training_data')
        synthetic_data = self.params.get('synthetic_data')
        prediction_column_name = self.params.get('prediction_column_name')
        real_validation_data = self.params.get('real_validation_data')
        
        # Custom implementation for regression data augmentation
        # Train on real data only (baseline)
        X_real = real_training_data.drop(columns=[prediction_column_name])
        y_real = real_training_data[prediction_column_name]

        # Train on augmented data (real + synthetic)
        augmented_data = pd.concat([real_training_data, synthetic_data], ignore_index=True)
        X_augmented = augmented_data.drop(columns=[prediction_column_name])
        y_augmented = augmented_data[prediction_column_name]

        # Validation data
        X_val = real_validation_data.drop(columns=[prediction_column_name])
        y_val = real_validation_data[prediction_column_name]

        # Train baseline model (real data only)
        baseline_model = ReproducibleOperations.get_random_forest_regressor()
        baseline_model.fit(X_real, y_real)
        baseline_pred = baseline_model.predict(X_val)
        baseline_r2 = r2_score(y_val, baseline_pred)
        baseline_mse = mean_squared_error(y_val, baseline_pred)
        baseline_mae = mean_absolute_error(y_val, baseline_pred)

        # Train augmented model (real + synthetic data)
        augmented_model = ReproducibleOperations.get_random_forest_regressor()
        augmented_model.fit(X_augmented, y_augmented)
        augmented_pred = augmented_model.predict(X_val)
        augmented_r2 = r2_score(y_val, augmented_pred)
        augmented_mse = mean_squared_error(y_val, augmented_pred)
        augmented_mae = mean_absolute_error(y_val, augmented_pred)

        # Compute improvement score normalized to [0, 1]:
        # fraction of the maximum possible R2 gain (from baseline to perfect R2=1) achieved by augmentation.
        # Negative improvements (augmentation hurts) are clipped to 0.
        # Floor the baseline at 0.0 (mean predictor)
        base = max(0.0, baseline_r2)
        aug = max(0.0, augmented_r2)

        # Calculate improvement relative to the remaining gap
        gap = 1.0 - base

        if gap > 1e-6: # Avoid division by zero
            # Gain relative to the possible room for improvement
            r2_improvement = (aug - base) / gap
            # Clip to [0, 1] - if aug < base, it's 0. If it exceeds 1.0 (unlikely), it's 1.
            score = max(0.0, min(1.0, r2_improvement))
        else:
            score = 0.0
        
        if self.params.get('notes', False):
            return score, { 'George': 'Removed MSE and MAE from the output. Focused solely on R2 improvement.' }
        return score
