from sdmetrics.reports.single_table import QualityReport
from synqtab.evaluators.Evaluator import Evaluator


class QualityEvaluator(Evaluator):
    """ Quality Evaluator that leverages SDMetrics QualityReport
        https://docs.sdv.dev/sdmetrics/data-metrics/quality/quality-report. Parameters:
        - [*required*] `'real_training_data'`: the real data used to train the generator
        - [*required*] `'synthetic_data'`: the synthetic data generated by the generator
        - [*required*] `'metadata'`: sdmetrics metadata; See 
        https://docs.sdv.dev/sdmetrics/getting-started/metadata/single-table-metadata
        - [*optional*] `'notes'`: True/False on whether to include notes in the result or not.
        If absent, defaults to False.
    """
        
    def compute_result(self):
        try:
            # Initialize the SDMetrics QualityReport
            quality_report = QualityReport()

            # Generate the report
            quality_report.generate(
                real_data = self.params.get('real_training_data'), 
                synthetic_data=self.params.get('synthetic_data'), 
                metadata=self.params.get('metadata'), 
                verbose=False
            )

            if not self.params.get('notes', False):
                return quality_report.get_score()

            # Get detailed property scores (Column Shapes, Column Pair Trends)
            report = dict()
            properties = quality_report.get_properties()
            for _, row in properties.iterrows():
                prop_name = row['Property']
                clean_prop_name = prop_name.replace(' ', '_')
                report[f'{clean_prop_name}_Score'] = row['Score']

                # Get details for this specific property and convert to dict/list for JSON serialization
                details = quality_report.get_details(property_name=prop_name)
                report[f'{clean_prop_name}_Details'] = details.to_dict(orient='records')

            return quality_report.get_score(), report

        except Exception as e:
            # TODO LOG ERROR
            report['QualityReport_error'] = str(e)
            return 0., report
